### ISSUE TITLE
Icons not visible with dark mode on mobile

### ISSUE THREAD

**Issue by piratenpanda** [piratenpanda/veggiekarte#101]
I was browsing the page this morning and noticed my Firefox was using some dark background on the menu icons and black icons for vegetarian friendly restaurants. Can we somehow disable dark mode switching or put proper icons?

**Comment by KristjanESPERANTO** [comment]
I tried a little bit not to accept the dark mode, but with no satisfying result.

It would be nicer anyway, as you say, if we could manage to support the dark mode properly. I just currently lack a bit of time.

**Comment by KristjanESPERANTO** [comment]
With Chrome, the buttons are fine in dark mode. Too bad that the browsers behave differently :slightly_frowning_face:

We can certainly solve this by using PNG instead of SVG or by using an icon font, but I don't really like either approach.

| Firefox | Chrome |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/35647502/200116526-4cb7aa8c-da30-4e30-9118-c7f81cb513bb.jpeg" alt="drawing" height="600"/> | <img src="https://user-images.githubusercontent.com/35647502/200116527-c775e97d-abed-41ff-89c1-17ac73afd28c.jpeg" alt="drawing" height="600"/> |

**Comment by piratenpanda** [comment]
Moved to https://codeberg.org/piratenpanda/veggiekarte/issues/101
