### ISSUE TITLE
Search works only once

### ISSUE THREAD

**Issue by tuukka** [piratenpanda/veggiekarte#81]
If I search for multiple places, the results will always be those of the first search I made. Does it also happen to you?

**Comment by piratenpanda** [comment]
Confirmed

**Comment by KristjanESPERANTO** [comment]
That is interesting. I can see this problem too (with Firefox and Chrome). As soon as I clear the cache, the search sometimes works without any problem and sometimes it occurs again immediately with the second search.

I get the same behavior when I take the unpkg packages from the geocoder plugin.

There doesn't seem to be a general problem with the plugin, because I can't observe the problem with a basic example of the geocoder plugin.

But with the old version 1.13.0 I couldn't see it till now.

At the moment I have no concrete idea how we can track it down. But using an old version of the plugin wouldn't be a good solution I think.
